<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-26T10:24:31Z" name="Suite" finished-at="2022-08-26T10:24:58Z" duration-ms="27236">
    <groups>
    </groups>
    <test started-at="2022-08-26T10:24:31Z" name="Stage" finished-at="2022-08-26T10:24:43Z" duration-ms="12046">
      <class name="script.ValidSignUp">
        <test-method is-config="true" signature="openApp(java.lang.reflect.Method, java.lang.String)[pri:0, instance:script.ValidSignUp@68c9d179]" started-at="2022-08-26T10:24:31Z" name="openApp" finished-at="2022-08-26T10:24:38Z" duration-ms="7551" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void script.ValidSignUp.testValidSignUp() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[stage.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testValidSignUp()[pri:0, instance:script.ValidSignUp@68c9d179]" started-at="2022-08-26T10:24:38Z" name="testValidSignUp" finished-at="2022-08-26T10:24:40Z" duration-ms="2227" status="FAIL">
          <exception class="org.openqa.selenium.interactions.MoveTargetOutOfBoundsException">
            <message>
              <![CDATA[Origin element is not displayed
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'LAPTOP-RI7JP09I', ip: '192.168.0.106', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.2'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [2589f557-7758-4693-a7bd-301ba1c45235, actions {actions=[org.openqa.selenium.interactions.Sequence@248abe23]}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 104.0, moz:accessibilityChecks: false, moz:buildID: 20220818191623, moz:debuggerAddress: localhost:54360, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 24420, moz:profile: C:\Users\Jisha\AppData\Loca..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:54360/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 2589f557-7758-4693-a7bd-301ba1c45235]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: Origin element is not displayed
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'LAPTOP-RI7JP09I', ip: '192.168.0.106', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.2'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [2589f557-7758-4693-a7bd-301ba1c45235, actions {actions=[org.openqa.selenium.interactions.Sequence@248abe23]}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 104.0, moz:accessibilityChecks: false, moz:buildID: 20220818191623, moz:debuggerAddress: localhost:54360, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 24420, moz:profile: C:\Users\Jisha\AppData\Loca..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:54360/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 2589f557-7758-4693-a7bd-301ba1c45235
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:615)
at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:567)
at org.openqa.selenium.interactions.Actions.perform(Actions.java:536)
at page.SignUpPage.joinClick(SignUpPage.java:56)
at script.ValidSignUp.testValidSignUp(ValidSignUp.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.interactions.MoveTargetOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidSignUp -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.ValidSignUp@68c9d179]" started-at="2022-08-26T10:24:41Z" name="closeApp" finished-at="2022-08-26T10:24:43Z" duration-ms="2235" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidSignUp status=FAILURE method=ValidSignUp.testValidSignUp()[pri:0, instance:script.ValidSignUp@68c9d179] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.ValidSignUp -->
    </test> <!-- Stage -->
    <test started-at="2022-08-26T10:24:31Z" name="UAT" finished-at="2022-08-26T10:24:58Z" duration-ms="27236">
      <class name="script.ValidSignUp">
        <test-method is-config="true" signature="createReport()[pri:0, instance:script.ValidSignUp@29d80d2b]" started-at="2022-08-26T10:24:30Z" name="createReport" finished-at="2022-08-26T10:24:31Z" duration-ms="362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createReport -->
        <test-method is-config="true" signature="openApp(java.lang.reflect.Method, java.lang.String)[pri:0, instance:script.ValidSignUp@29d80d2b]" started-at="2022-08-26T10:24:31Z" name="openApp" finished-at="2022-08-26T10:24:44Z" duration-ms="13007" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void script.ValidSignUp.testValidSignUp() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[uat.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testValidSignUp()[pri:0, instance:script.ValidSignUp@29d80d2b]" started-at="2022-08-26T10:24:44Z" name="testValidSignUp" finished-at="2022-08-26T10:24:57Z" duration-ms="13235" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is Failed: Recheck the entered details on sign up page again]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is Failed: Recheck the entered details on sign up page again
at org.testng.Assert.fail(Assert.java:96)
at script.ValidSignUp.testValidSignUp(ValidSignUp.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidSignUp -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.ValidSignUp@29d80d2b]" started-at="2022-08-26T10:24:57Z" name="closeApp" finished-at="2022-08-26T10:24:58Z" duration-ms="977" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidSignUp status=FAILURE method=ValidSignUp.testValidSignUp()[pri:0, instance:script.ValidSignUp@29d80d2b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="publishReport()[pri:0, instance:script.ValidSignUp@29d80d2b]" started-at="2022-08-26T10:24:58Z" name="publishReport" finished-at="2022-08-26T10:24:58Z" duration-ms="393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- publishReport -->
      </class> <!-- script.ValidSignUp -->
    </test> <!-- UAT -->
  </suite> <!-- Suite -->
</testng-results>
