<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-15T11:06:27Z" name="Default suite" finished-at="2023-05-15T11:06:52Z" duration-ms="25722">
    <groups>
    </groups>
    <test started-at="2023-05-15T11:06:27Z" name="Default test" finished-at="2023-05-15T11:06:52Z" duration-ms="25722">
      <class name="script.ValidSignIn">
        <test-method is-config="true" signature="createReport()[pri:0, instance:script.ValidSignIn@7daa0fbd]" started-at="2023-05-15T11:06:26Z" name="createReport" finished-at="2023-05-15T11:06:27Z" duration-ms="334" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createReport -->
        <test-method is-config="true" signature="openApp(java.lang.reflect.Method, java.lang.String)[pri:0, instance:script.ValidSignIn@7daa0fbd]" started-at="2023-05-15T11:06:27Z" name="openApp" finished-at="2023-05-15T11:06:44Z" duration-ms="17429" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void script.ValidSignIn.testValidSignIn() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[stage.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testValidSignIn()[pri:4, instance:script.ValidSignIn@7daa0fbd]" started-at="2023-05-15T11:06:44Z" name="testValidSignIn" finished-at="2023-05-15T11:06:51Z" duration-ms="7024" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is Failed: Please verify the entered user credentials.  Unable to login]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is Failed: Please verify the entered user credentials.  Unable to login
at org.testng.Assert.fail(Assert.java:96)
at script.ValidSignIn.testValidSignIn(ValidSignIn.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidSignIn -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.ValidSignIn@7daa0fbd]" started-at="2023-05-15T11:06:51Z" name="closeApp" finished-at="2023-05-15T11:06:52Z" duration-ms="1239" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidSignIn status=FAILURE method=ValidSignIn.testValidSignIn()[pri:4, instance:script.ValidSignIn@7daa0fbd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="publishReport()[pri:0, instance:script.ValidSignIn@7daa0fbd]" started-at="2023-05-15T11:06:53Z" name="publishReport" finished-at="2023-05-15T11:06:53Z" duration-ms="878" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- publishReport -->
      </class> <!-- script.ValidSignIn -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
